const I18N = {
en: {
  "nav.services": "Services",
  "nav.why": "Why us",
  "nav.gallery": "Gallery",
  "nav.faq": "FAQ",
  "nav.reviews": "Reviews",
  "nav.contact": "Contact",
  "nav.call": "+965 9789 2408",
  "nav.whatsapp": "WhatsApp",
  "hero.kicker": "Hawalli, Kuwait · AC technicians",
  "hero.title": "Cool air back on,<br>same-day service.",
  "hero.sub": "AC repair, servicing and installation across Hawalli and Kuwait City — split and central systems, genuine parts, and fair prices quoted before we start.",
  "hero.cta1": "Book a visit",
  "hero.cta2": "WhatsApp us",
  "trust.t1t": "WhatsApp us",
  "trust.t1d": "+965 9789 2408",
  "trust.t2t": "AC repair · service",
  "trust.t2d": "Split & central systems",
  "trust.t3t": "Hawalli based",
  "trust.t3d": "Serving all of Kuwait",
  "stats.samedayNum": "Same-day visits",
  "stats.sameday": "across Hawalli",
  "stats.tradesNum": "Split &amp; central AC",
  "stats.trades": "repair specialists",
  "stats.rateNum": "Genuine parts",
  "stats.rate": "quoted before work",
  "stats.visitNum": "All major brands",
  "stats.visit": "serviced &amp; repaired",
  "services.kicker": "What we do",
  "services.title": "Installation and repair, done right",
  "services.s1t": "AC repair",
  "services.s1d": "Split and central ACs diagnosed and repaired — fast and properly.",
  "services.s2t": "AC servicing",
  "services.s2d": "Deep cleaning of coils, filters and drains for stronger cooling.",
  "services.s3t": "AC installation",
  "services.s3d": "New split ACs installed neatly and commissioned correctly.",
  "services.s4t": "Gas refilling",
  "services.s4d": "Refrigerant top-ups and leak checks for weak cooling.",
  "services.s5t": "Duct cleaning",
  "services.s5d": "Cleaner ducts and vents for better airflow and air quality.",
  "services.s6t": "Annual maintenance",
  "services.s6d": "Year-round maintenance plans that keep breakdowns away.",
  "why.kicker": "Why choose us",
  "why.title": "Cool air, no drama",
  "why.intro": "When the AC dies in a Kuwait summer, you need it fixed today — our Hawalli technicians arrive with the parts, quote before they start, and cool your home back down.",
  "why.l1t": "Fast Hawalli response",
  "why.l1d": "Based locally — quick visits across Hawalli and Kuwait City.",
  "why.l2t": "Upfront pricing",
  "why.l2d": "You approve the price before we begin — no surprises.",
  "why.l3t": "Genuine parts",
  "why.l3d": "Quality spares that last, fitted correctly the first time.",
  "why.l4t": "WhatsApp booking",
  "why.l4d": "Message us on +965 9789 2408 — send a photo of the unit.",
  "gallery.kicker": "Our work",
  "gallery.title": "Neat work, done properly",
  "gallery.c1": "Coils cleaned for stronger cooling",
  "gallery.c2": "Control panels and vents set right",
  "gallery.c3": "Split units installed neatly",
  "reviews.kicker": "What people say",
  "reviews.title": "Trusted across Hawalli",
  "reviews.more": "Find us on Google — see our location and reviews",
  "faq.kicker": "Good to know",
  "faq.title": "Frequently asked questions",
  "faq.q1": "Which areas do you serve?",
  "faq.a1": "We are based in Hawalli and serve homes and offices across Kuwait.",
  "faq.q2": "Do you give quotes before starting?",
  "faq.a2": "Yes — you approve the price before we begin any work. No surprises.",
  "faq.q3": "Which brands do you service?",
  "faq.a3": "All major split and central AC brands — parts fitted are quality spares.",
  "faq.q4": "How do I book a visit?",
  "faq.a4": "Call or WhatsApp us on +965 9789 2408 — send a photo of your unit and we will quote.",
  "contact.kicker": "Get in touch",
  "contact.title": "Book your visit",
  "contact.addr": "Address",
  "contact.phone": "Phone",
  "contact.hours": "Hours",
  "contact.hoursVal": "Hours: by appointment | Call for availability",
  "contact.cta": "Call to book",
  "contact.cta2": "WhatsApp us",
  "footer.tag": "AC repair & service · Hawalli, Kuwait"
}};

document.addEventListener("DOMContentLoaded", function () {
  var btn = document.getElementById("menuBtn");
  var nav = document.getElementById("mainNav");
  if (btn && nav) { btn.addEventListener("click", function () { nav.classList.toggle("open"); }); }
  nav && nav.querySelectorAll("a").forEach(function (a) { a.addEventListener("click", function () { nav.classList.remove("open"); }); });
  var dict = I18N.en || {};
  document.querySelectorAll("[data-i18n]").forEach(function (el) {
    var k = el.getAttribute("data-i18n");
    if (dict[k] !== undefined) { el.innerHTML = dict[k]; }
  });
});
